parameters:   
  - name: artifactName
    type: string
    
  - name: archiveFile
    type: string
  
  - name: bundleDirectory
    type: string    

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: CopyFiles@2
    displayName: 'Copy needed files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        Dependencies/databricks_cli/**
        ${{ parameters.bundleDirectory }}/**
      TargetFolder: '$(Pipeline.Workspace)/build'
      CleanTargetFolder: true
      OverWrite: true

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(Pipeline.Workspace)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.archiveFile }}'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ${{ parameters.artifactName }}'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: ${{ parameters.artifactName }}