parameters:
  - name: environment
    type: string
          
jobs:
- job: NSLookup
  displayName: NSLookup ${{ parameters.environment }}
  
  variables:
    - template: ../Configuration/${{ parameters.environment }}.variables.yml  
  
  pool:
    name: ${{ variables.poolName }}
    environment: ${{ parameters.environment }}

  steps:
  - download: none

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $hostname = "${{ variables.host }}"
        $hostname = $hostname.Replace("https://", "").Replace("http://", "")
        Write-Host $hostname
        nslookup $hostname    